package com.jovi.photoai.ui

enum class AppDestination {
    HOME,
    PROJECT_IMPORT,
    PROJECT_BOARD,
    PROJECT_SUMMARY,
    CAPTURE_ENTRY,
    REFERENCE_LIBRARY,
    IMPORT_REFERENCE,
    ANALYSIS_DETAIL,
    DIRECTOR_CARD,
    CAMERA_DIRECTOR,
    DIRECT_CAPTURE,
}
